### ISSUE TITLE
Empty project

### ISSUE THREAD

**Issue by VadimsMalickis** [EdgarsBe/edgarsbe.github.io#1]
Atgādiniet lūdzu kā Jums sanāca 6 par oktobri?
    Varat vienkārši uzrakstīt komentāru šeit.

    Un protams vajadzētu ielādēt projektu uz Jūsu repo.

**Comment by EdgarsBe** [comment]
Jūs apskatījāt stundas laikā manu mājaslapu kur bija izveidots headers un footers, bet githuba tas netika ielikts

**Comment by VadimsMalickis** [comment]
Labi, bet varat lūdzu ielikt kodu githubā, lai sekotu līdzi kā projekts attīstās. @EdgarsBe
